### ISSUE TITLE
大佬，这个云开发的小程序还需要后台服务器吗？

### ISSUE THREAD

**Issue by jljaoe** [TencentCloudBase/tcb-demo-message#2]
大佬，这个云开发的小程序还需要后台服务器吗？我怎么都不成功呢，错误提示invalid credential, access_token is invalid or not latest hint: [kp4ehA0963vr69!]，在微信公众平台这里还需要设置url和token什么的吗？求解决，也同求定时推送。谢谢大佬，有空搞个！

**Comment by lcxfs1991** [comment]
这里的secretID 和 secretKey，是需要拿腾讯云的。
云开发不需要服务器

**Comment by jljaoe** [comment]
云开发小程序我已经有一个练手小项目了，可是我还是没找到secretID和secretKey在哪里填入，腾讯云的我已经拿到了。大佬可不可以介绍详细一点，真心感谢！

**Comment by lcxfs1991** [comment]
这个demo，有对应的文章解释，请参考：
https://github.com/TencentCloudBase/mp-book/blob/master/medium-tutorial/sms.md

欢迎给个star呀
